// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Towns.webapi.DatabaseContext;

#nullable disable

namespace Towns.webapi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241009204657_Initital")]
    partial class Initital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Towns.webapi.Models.Town", b =>
                {
                    b.Property<Guid>("TownID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TownName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TownID");

                    b.ToTable("Towns", (string)null);

                    b.HasData(
                        new
                        {
                            TownID = new Guid("0d071e81-29ff-4c8c-999d-fddcc1423bc3"),
                            TownName = "Plumtree"
                        },
                        new
                        {
                            TownID = new Guid("4d99a283-6e7f-4fcc-a548-c9f521f4dfb0"),
                            TownName = "Bulawayo"
                        },
                        new
                        {
                            TownID = new Guid("7b1442fd-356f-4871-8c88-bcce0b8e5410"),
                            TownName = "Gaborone"
                        },
                        new
                        {
                            TownID = new Guid("61766988-2121-440b-ac8a-bd0d37d13c7c"),
                            TownName = "Mochudi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
